//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBSync.Models.OBDataSources
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AllMyBioDbEntities : DbContext
    {
        public AllMyBioDbEntities()
            : base("name=AllMyBioDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AllMyBio.domain> domains { get; set; }
        public virtual DbSet<AllMyBio.link> links { get; set; }
        public virtual DbSet<AllMyBio.package> packages { get; set; }
        public virtual DbSet<AllMyBio.page> pages { get; set; }
        public virtual DbSet<AllMyBio.payment> payments { get; set; }
        public virtual DbSet<AllMyBio.project> projects { get; set; }
        public virtual DbSet<AllMyBio.setting> settings { get; set; }
        public virtual DbSet<AllMyBio.track_links> track_links { get; set; }
        public virtual DbSet<AllMyBio.user> users { get; set; }
        public virtual DbSet<AllMyBio.users_logs> users_logs { get; set; }
    }
}
