//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMBMigrater.AMBDataSources.AMB4
{
    using System;
    using System.Collections.Generic;
    
    public partial class code
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public code()
        {
            this.redeemed_codes = new HashSet<redeemed_codes>();
        }
    
        public int code_id { get; set; }
        public string type { get; set; }
        public Nullable<int> days { get; set; }
        public Nullable<int> package_id { get; set; }
        public string code1 { get; set; }
        public int discount { get; set; }
        public int quantity { get; set; }
        public int redeemed { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual package package { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<redeemed_codes> redeemed_codes { get; set; }
    }
}
