//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMBMigrater.AMBDataSources.AMB4
{
    using System;
    using System.Collections.Generic;
    
    public partial class page
    {
        public int page_id { get; set; }
        public Nullable<int> pages_category_id { get; set; }
        public string title { get; set; }
        public string url { get; set; }
        public string description { get; set; }
        public string content { get; set; }
        public string type { get; set; }
        public string position { get; set; }
        public Nullable<int> order { get; set; }
        public Nullable<int> total_views { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<System.DateTime> last_date { get; set; }
    
        public virtual pages_categories pages_categories { get; set; }
    }
}
