//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMBMigrater.AMBDataSources.AMB6
{
    using System;
    using System.Collections.Generic;
    
    public partial class pages_categories
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pages_categories()
        {
            this.pages = new HashSet<page>();
        }
    
        public int pages_category_id { get; set; }
        public string url { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string icon { get; set; }
        public int order { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<page> pages { get; set; }
    }
}
