//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMBMigrater.AMBDataSources.AMB6
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment
    {
        public long id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> plan_id { get; set; }
        public string processor { get; set; }
        public string type { get; set; }
        public string frequency { get; set; }
        public string payment_id { get; set; }
        public string subscription_id { get; set; }
        public string payer_id { get; set; }
        public string email { get; set; }
        public string name { get; set; }
        public string billing { get; set; }
        public string taxes_ids { get; set; }
        public Nullable<float> base_amount { get; set; }
        public Nullable<float> total_amount { get; set; }
        public string code { get; set; }
        public Nullable<float> discount_amount { get; set; }
        public string currency { get; set; }
        public string payment_proof { get; set; }
        public Nullable<sbyte> status { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual plan plan { get; set; }
        public virtual user user { get; set; }
    }
}
