//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMBMigrater.AMBDataSources.AMB6
{
    using System;
    using System.Collections.Generic;
    
    public partial class redeemed_codes
    {
        public int id { get; set; }
        public int code_id { get; set; }
        public int user_id { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual code code { get; set; }
        public virtual user user { get; set; }
    }
}
